POST https://inostar.herokuapp.com/download/download
Content-Type: application/json

{
    "name": "RetroArch.1.10.6.msvc2019.7z",
    "url": "https://github.com/basharast/RetroArch-ARM/releases/download/1.10.6a/RetroArch.1.10.6.msvc2019.7z"
}

###
