POST https://inostar.herokuapp.com/download/download
Content-Type: application/json

{
    "name": "EmuELEC-Amlogic-ng.aarch64-4.5-Generic.img.gz",
    "url": "https://github.com/EmuELEC/EmuELEC/releases/download/v4.5/EmuELEC-Amlogic-ng.aarch64-4.5-Generic.img.gz"
}

###
